name: cd

on:
  workflow_dispatch:
    inputs:
      validate_only:
        description: 'Run validation only (no release)'
        required: false
        default: false
        type: boolean
  check_run:
    types:
      - completed

permissions:
  checks: read
  contents: write

jobs:
  maven-cd:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    with:
      validate_only: ${{ inputs.validate_only || false }}
    secrets: inherit
